### PR TITLE
Full joystick/gamepad control

### PR DESCRIPTION
**Pull request by protocultor**
- Joystick is enabled by default
- Menus can be fully controlled with it, without the need for "enter" and "esc" keys
- "Main menu" and "pause" can be bind to a button in the options
These changes allow for a completely keyboard-free configuration of the game.

### CODE REVIEW

**Comment by protocultor** [comment]
Binaries can be obtained directly here: https://github.com/protocultor/zdoom/releases/tag/2.8.11

**Comment by protocultor** [comment]
New changes allow to exit the end of an episode with a gamepad, the only instance I found it wasn't responding.
New binaries here: https://github.com/protocultor/zdoom/releases/tag/2.8.12

**Comment by protocultor** [comment]
Sorry about the close, clicked in the wrong button.

**Comment by joolswills** [comment]
This will need to be revisited. We are moving to lzdoom and zdoom is being removed (it's already happened on our fkms_rpi4 development branch).

This is based of https://github.com/drfrag666/gzdoom - branch 3.82

**Comment by protocultor** [comment]
Ok. This has been replaced with:
https://github.com/protocultor/gzdoom/tree/joypad_menu

**Pull request closed without merging**
